--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/cian/Pictures/blocks-and-crickets.jpg"

-- Special
background="#3b2f45"
foreground="#e4c7d9"
cursor="#e4c7d9"

-- Colors
color0="#3b2f45"
color1="#E9918E"
color2="#CFB497"
color3="#EDB299"
color4="#DEA4A8"
color5="#E3CF9C"
color6="#F3D2AE"
color7="#e4c7d9"
color8="#9f8b97"
color9="#E9918E"
color10="#CFB497"
color11="#EDB299"
color12="#DEA4A8"
color13="#E3CF9C"
color14="#F3D2AE"
color15="#e4c7d9"
