# Shell variables
# Generated by 'wal'
wallpaper='/home/cian/Pictures/blocks-and-crickets.jpg'

# Special
background='#3b2f45'
foreground='#e4c7d9'
cursor='#e4c7d9'

# Colors
color0='#3b2f45'
color1='#E9918E'
color2='#CFB497'
color3='#EDB299'
color4='#DEA4A8'
color5='#E3CF9C'
color6='#F3D2AE'
color7='#e4c7d9'
color8='#9f8b97'
color9='#E9918E'
color10='#CFB497'
color11='#EDB299'
color12='#DEA4A8'
color13='#E3CF9C'
color14='#F3D2AE'
color15='#e4c7d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
